PHR/urls.py
from django.urls import path
from django.contrib import admin
from PHR import views
from django.conf.urls.static import static
from django.conf import settings
#from . import views

app_name = 'PHR'
"""urlpatterns = [
    path('', views.IndexView.as_view(), name= 'index'),
]"""
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index),
    path('edit/', views.phr),
    path('register/', views.register),
    #path('login/', views.login, name='login'),
    path('logout/', views.logout),
    path('Height_Record/', views.HeightRecord),
    path('Weight_Record/', views.WeightRecord),
    path('Temperature_Record/', views.TemperatureRecord),
    path('Steps_Record/', views.StepsRecord),
    path('BMI_Record/', views.BMIRecord),
    path('BloodPressure_Record/', views.BloodPressureRecord),
    path('HeartRate_Record/', views.HeartRateRecord),
    path('Respiration_Record/', views.RespirationRecord),
    path('Smoking_Record/', views.SmokingRecord),
    path('Height_Record_VitalSign/', views.HeightRecordVitalSign),
    path('Weight_Record_VitalSign/', views.WeightRecordVitalSign),
    path('Temperature_Record_VitalSign/', views.TemperatureRecordVitalSign),
    path('Steps_Record_VitalSign/', views.StepsRecordVitalSign),
    path('BMI_Record/_VitalSign', views.BMIRecordVitalSign),
    path('BloodPressure_Record_VitalSign/', views.BloodPressureRecordVitalSign),
    path('HeartRate_Record_VitalSign/', views.HeartRateRecordVitalSign),
    path('Respiration_Record_VitalSign/', views.RespirationRecordVitalSign),
    path('Smoking_Record_VitalSign/', views.SmokingRecordVitalSign),
    path('Imaging_History/', views.ImagingHistory),
    path('Laboratory_History/', views.LaboratoryHistory),
    path('Medications_History/', views.MedicationsHistory),
    path('Allergies_History/', views.AllergiesHistory),
    path('Diagnosis_History/', views.DiagnosisHistory),
    path('Visit/<str:En_id>/', views.Visit, name='Visit'),
    path('Visit/ImagingFile/<str:FileCode>/', views.ImagingFile, name='ImagingFile'),
    path('Visit/LaboratoryFile/<str:FileCode>/', views.LaboratoryFile, name='LaboratoryFile'),
    path('Auditable_Records/', views.AuditableRecords),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

PHR/models.py
from django.db import models
import datetime
from django.utils import timezone


class User(models.Model):
    #ID = (('Doctor', "Doctor"), ('Patient', "Patient"))
    u_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=200, unique=True)
    password = models.CharField(max_length=256)
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username
    def set_list(self, info, element):
        #add new patient
        if info == "pid":
            if self.pid_data != "":
                self.pid_data = self.pid_data + "," + element
            else:
                self.pid_data = element
    def get_list(self, info):
        if info == "pid":
            if self.pid_data != "":
                return self.pid_data.split(",")
            else:
                None
    class Meta:
        ordering = ["-c_time"]
        verbose_name = "Users"


class Patient(models.Model):
    p_id = models.AutoField(primary_key=True)
    cid = models.ForeignKey(to='User', to_field="u_id", related_name="patient", on_delete=models.CASCADE, default=None)
    add_time = models.CharField(max_length=30, null=True)
    name = models.CharField(max_length=200)
    cc_time = models.DateTimeField(auto_now=True)
    phoneNumber = models.CharField(max_length=200, default="")
    NHINumber = models.CharField(max_length=200, default="")
    organization_id = models.TextField(max_length=200, default="")

    def __str__(self):
        return self.name



    class Meta:
        ordering = ["-cc_time"]
        verbose_name = "Patients"

class ActionLog(models.Model):
    user = models.ForeignKey(to='User', to_field="u_id", on_delete=models.CASCADE, null=True, blank=True)
    action = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.timestamp} - {self.user.u_id if self.user else 'None'} - {self.user if self.user else 'Anonymous'} - {self.action}"
    class Meta:
        ordering = ["-timestamp"]
        verbose_name = "Action Log"


#class HealthRecord(models.Model):

# Create your models here.

PHR/templates/Diagnosis_History.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- 上述meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
        <!-- Bootstrap CSS -->
        <!-- <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"> -->

        <link href="{% static 'index/css/index.css' %}" rel="stylesheet"/>
        <style>
            .button:focus {
                outline: none;
                box-shadow: none;
            }
            ul {
                list-style-type: none;
                margin: 0;
                padding: 0;
                overflow: hidden;
                background-color: rgba(247, 247, 247, 0.8);
            }

            li {
                float: left;
            }

            li a {
                display: block;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }
            /*
            a,a:hover,a:active,a:visited,a:link,a:focus{
                -webkit-tap-highlight-color:rgba(0,0,0,0);
                -webkit-tap-highlight-color: transparent;
                outline:none;
                background: none;
                text-decoration: none;
            }background:#0000ff61;
            */


            .back:hover{
                color:#fff;
                background-color:#b3d7ff;
                border-color:#b3d7ff;
                text-decoration: none;
            }
            .table td, .table th {
                padding: 0.35rem;
            }

        </style>
        <style>
          .imaging_wapper thead{
            color: #909399!important;
            font-size:14px!important;
          }
          .operate_wapper td{
            line-height: 0.5;
            font-size: 12px;
            display: inline-block;
          }
          .btn-primary{
            line-height:auto;
            padding: 0.3rem 0.6rem;
          }
          table{
          color:#606266!important;
          }
          
        </style>
        <title>Diagnosis History</title>
    </head>
    <body>
        <ul>
            <li><a href="/PHR/index/" class="back">< Back</a></li>
            <li style="margin-left: 15%;">
                <h1 style="display: block;text-align: center;
                    padding: 14px 16px;color:#030303;font-size: 16px;font-family: Helvetica-bold;float: none;
                    font-weight: bold;">
                    Diagnosis
                </h1>
            </li>
        </ul>

        <div class="container imaging_wapper" style="padding: 0.2rem;overflow-y: auto;">
            <table class="table table-striped" style="line-height: 10px;font-size: 12px;text-align: center;font-family: Arial;">
                <thead style="color: rgba(0, 118, 255, 1);font-size: 13px;text-align: left;font-family: PingFangSC-regular;">
                <tr>
                    <th scope="col" style="font-weight:normal;
                    line-height: 18px;width:30%;border-right: 1px solid #ebeef5;">
                        Disease
                    </th>

                    <th scope="col" style="font-weight:normal;
                    line-height: 18px;width:40%;border-right: 1px solid #ebeef5;">
                        Date
                    </th>
                    <th scope="col"  style="font-weight:normal;
                    line-height: 18px;width:15%;border-right: 1px solid #ebeef5;">
                        Doctor
                    </th>
                    <th scope="col"  style="font-weight:normal;
                    line-height: 18px;width:15%;">
                        Link
                    </th>
                </tr>
                </thead>
                <tbody>

                {% for d1,disease,t,Doctor,En_id in En_All_DataList %}
                <tr>
                    <td style="vertical-align: middle;font-size: 12px;word-break: break-all;text-align:left;">
                        {{d1}}
                    </td>
                    <td style="vertical-align: middle;font-size: 12px;word-break: break-all;">
                        {{t}}
                    </td>
                    <td style="vertical-align: middle;font-size: 12px;">
                        {{Doctor}}
                    </td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'PHR:Visit' En_id %}" style="line-height: 0.5;font-size: 12px;">Link</a>
                    </td>
                </tr>
                {% if disease %}
                {% for i in disease %}
                <tr>

                    <td style="vertical-align: middle;font-size: 12px;word-break: break-all;text-align:left;" colspan="4">
                        {{i}}
                    </td>
                </tr>
                {% endfor %}
                {% endif %}
                {% empty %}
                <tr>
                    <td style="vertical-align: middle;font-size: 12px;word-break: break-all;text-align:left;">
                        None
                    </td>

                    <td style="vertical-align: middle;font-size: 12px;">
                        None
                    </td>
                    <td>
                        <a class="btn btn-primary" href="" style="line-height: 0.5;font-size: 12px;">Link</a>
                    </td>
                </tr>
                <tr>

                    <td style="vertical-align: middle;font-size: 12px;word-break: break-all;text-align:left;" colspan="4">
                        None
                    </td>
                </tr>


                {% endfor %}
                </tbody>
            </table>
        </div>


        <script src="https://cdn.staticfile.org/echarts/4.3.0/echarts.min.js"></script>
        <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
        <script src="https://cdn.bootcss.com/popper.js/1.15.0/umd/popper.js"></script>
        <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="https://cdn.staticfile.org/echarts/4.3.0/echarts.min.js"></script>
        <script type="text/javascript">
        </script>
    </body>
</html>

PHR/templates/ImagingFile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- 上述meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
        <!-- Bootstrap CSS -->
        <!-- <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"> -->

        <link href="{% static 'index/css/index.css' %}" rel="stylesheet"/>

        <style>
            .nav-link:focus {
                outline: none;
                box-shadow: none;
            }
            .button:focus {
                outline: none;
            }

            .back:hover{
                color:#fff;
                background-color:#b3d7ff;
                border-color:#b3d7ff;
                text-decoration: none;
            }
            ul {
                list-style-type: none;
                margin: 0;
                padding: 0;
                overflow: hidden;
                background-color: rgba(247, 247, 247, 0.8);
            }

            li {
                float: left;
            }
            .table td, .table th {
                padding: 0.15rem;
            }
            li a {
                display: block;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }
            .col-3 {
                padding-right: 10px;
                padding-left: 10px;
            }

            .nav-link{
                color: #007BFF;
                background-color:white;
            }
        </style>
        <style>
          .row{
            margin: 0;
            padding: 0;
          }
          .container{
            padding:0;
          }
          .container button{
            font-size: 0.8rem;
            padding: 0.3rem 1.4rem;
            border:1px solid #c0c4cc;
          }
          #p-group{
            justify-content: center;
            padding: 0.6rem 0;
          }
          .gip{
            box-sizing: border-box;
            width100%;
            margin:0 1rem;
            height: 0.1rem;
            background-color: #dcdfe6;
          }
          .image_wapper{
            padding: 1rem;
            width: 100%;
          }
          .image_wapper img{
            width:100%;
            object-fit: contain;
          }

        </style>
        <title>Imaging File</title>
    </head>
    <body style="">
        <ul>
            <li><a href="{% url 'PHR:Visit' Encounter %}" class="back">< Back</a></li>
        </ul>
        {% comment %} <div class="row">
                <div class="col-4"></div>

            </div> {% endcomment %}
        <div class="container" >
          <ul id="p-group" class="nav nav-pills mb-3" role="tablist" style="background-color:white;">
            <li class="nav-item" role="presentation">
                <button class="nav-link active" id="PDF-tab" data-toggle="tab" data-target="#PDF" type="button" role="tab" aria-controls="PDF" aria-selected="true">PDF</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="Imaging-tab" data-toggle="tab" data-target="#Imaging" type="button" role="tab" aria-controls="Imaging" aria-selected="false" >Imaging</button>
            </li>
        </ul>
            {% comment %} <ul id="p-group" class="nav nav-pills mb-3" role="tablist" style="text-align:center;background-color:white;">
                <li class="nav-item" role="presentation" style="margin-left: auto;">
                    <button class="nav-link active" id="PDF-tab" data-toggle="tab" data-target="#PDF" role="tab"
                            aria-controls="PDF" aria-selected="true" style="width:71px;font-size: 12px;
                            text-align: center;font-family: Arial;padding-left: 0px;padding-right: 0px;
                            line-height: 10px;border-radius: 5px;border: 1px solid rgba(187, 187, 187, 1);">
                        PDF
                    </button>
                </li>
                <li class="nav-item" role="presentation" style="margin-right: auto;">
                    <button class="nav-link" id="Imaging-tab" data-toggle="tab" data-target="#Imaging" type="button" role="tab"
                            aria-controls="Imaging" aria-selected="false" style="width:71px;font-size: 12px;
                            text-align: center;font-family: Arial;padding-left: 0px;padding-right: 0px;
                            line-height: 10px;border-radius: 5px;border: 1px solid rgba(187, 187, 187, 1);">
                        Imaging
                    </button>
                </li>
            </ul> {% endcomment %}
            {% comment %} <div class="row">
                <div class="col-4"></div>
                <div class="col-4" style="border-bottom: 1px solid #82848F; margin-top: 1rem;"></div>
            </div> {% endcomment %}
            <div class="gip"></div>
            <div class="tab-content" style="overflow-y: auto;width:100%;">
                <div class="tab-pane active" id="PDF" role="tabpanel" aria-labelledby="PDF-tab" style="">
                    <div id="pdfContainer" class="container" style="padding: 0.2rem;">

                    </div>
                </div>

                <div class="tab-pane" id="Imaging" role="tabpanel" aria-labelledby="Imaging-tab">
                    <div class="container image_wapper">
                        {% for i in Imaging_DataList %}
                        <img src="data:image/png;base64,{{ i }}" alt="Image" >
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>


        <script src="https://cdn.staticfile.org/echarts/4.3.0/echarts.min.js"></script>
        <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
        <script src="https://cdn.bootcss.com/popper.js/1.15.0/umd/popper.js"></script>
        <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="https://cdn.staticfile.org/echarts/4.3.0/echarts.min.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js"></script>
        <script type="text/javascript">
            console.log(11);
            var PDF_DataList = '{{ PDF_DataList | safe}}';
            console.log(PDF_DataList);
            console.log("1");
            var binaryData = atob(PDF_DataList);

            var loadingTask = pdfjsLib.getDocument({data: binaryData});

            loadingTask.promise.then(function(pdf) {
                var numPages = pdf.numPages;
                var container = document.getElementById("pdfContainer")
              // Loop through each page
                for (let pageNum = 1; pageNum <= numPages; pageNum++) {
                pdf.getPage(pageNum).then(function(page) {
                    var scale = 1;
                    var viewport = page.getViewport({ scale: scale });

                    // Create a new canvas for each page
                    var canvas = document.createElement("canvas");

                    container.appendChild(canvas);
                    var context = canvas.getContext("2d");
                    canvas.height = viewport.height;
                    canvas.width = viewport.width;

                    var renderContext = {
                        canvasContext: context,
                        viewport: viewport
                    };
                    page.render(renderContext);
                });
              }
            }).catch(function(reason) {
              console.error(reason);
            });
        </script>
    </body>
</html>

PHR/templates/Laboratory_History.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- 上述meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
        <!-- Bootstrap CSS -->
        <!-- <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"> -->

        <link href="{% static 'index/css/index.css' %}" rel="stylesheet"/>
        <style>
            .button:focus {
                outline: none;
                box-shadow: none;
            }
            ul {
                list-style-type: none;
                margin: 0;
                padding: 0;
                overflow: hidden;
                background-color: rgba(247, 247, 247, 0.8);
            }

            li {
                float: left;
            }

            li a {
                display: block;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }
            /*
            a,a:hover,a:active,a:visited,a:link,a:focus{
                -webkit-tap-highlight-color:rgba(0,0,0,0);
                -webkit-tap-highlight-color: transparent;
                outline:none;
                background: none;
                text-decoration: none;
            }background:#0000ff61;
            */


            .back:hover{
                color:#fff;
                background-color:#b3d7ff;
                border-color:#b3d7ff;
                text-decoration: none;
            }
            .table td, .table th {
                padding: 0.35rem;
            }

        </style>
        <style>
          .imaging_wapper thead{
            color: #909399!important;
            font-size:14px!important;
          }
          .operate_wapper td{
            line-height: 0.5;
            font-size: 12px;
            display: inline-block;
          }
          .btn-primary{
            line-height:auto;
            padding: 0.3rem 0.6rem;
          }
          table{
          color:#606266!important;
          }
          
        </style>
        <title>Laboratory History</title>
    </head>
    <body>
        <ul>
            <li><a  class="back" onclick="window.history.go(-1)">< Back</a></li>
            <li style="margin-left: 15%;">
                <h1 style="display: block;text-align: center;
                    padding: 14px 16px;color:#030303;font-size: 16px;font-family: Helvetica-bold;float: none;
                    font-weight: bold;">
                    Laboratory
                </h1>
            </li>
        </ul>

        <div class="container imaging_wapper" style="padding:0;overflow-y: auto;">
            <table class="table table-striped" style="line-height: 10px;font-size: 16px;text-align: center;font-family: Arial;">
                <thead style="color: rgba(0, 118, 255, 1);font-size: 14px;text-align: left;font-family: PingFangSC-regular;">
                <tr>
                    <th scope="col" style="font-weight:normal;
                    line-height: 18px;width:25%;border-right: 1px solid #ebeef5;">
                        Items
                    </th>
                    <th scope="col" style="font-weight:normal;
                    line-height: 18px;width:25%;border-right: 1px solid #ebeef5;">
                        DATE
                    </th>
                    <th scope="col" style="font-weight:normal;
                    line-height: 18px;width:10%;border-right: 1px solid #ebeef5;">
                        Flag
                    </th>
                    <th scope="col" style="font-weight:normal;
                    line-height: 18px;width:20%;border-right: 1px solid #ebeef5;">
                        Report
                    </th>
                    <th scope="col" style="font-weight:normal;
                    line-height: 18px;width:20%;">
                        Link
                    </th>
                </tr>
                </thead>
                <tbody>

                {% for name,t,flag,En_id,Record_ID in Laboratory_DataList1 %}
                <tr>
                    <td style="vertical-align: middle;font-size: 12px;word-break: break-all;">
                        {{name}}
                    </td>
                    <td style="vertical-align: middle;font-size: 12px;word-break: break-all;">
                        {{t}}
                    </td>
                    <td style="vertical-align: middle;font-size: 12px;word-break: break-all;">
                        {{flag}}
                    </td>
                    <form  method="post" action="{% url 'PHR:LaboratoryFile' Record_ID %}" novalidate>
                        {% csrf_token %}
                        <td>
                            <button class="btn btn-primary" type="submit" name="Report" style="line-height: 0.5;font-size: 12px;">Link</button>
                        </td>
                    </form>
                    <td>
                        <a class="btn btn-primary" href="{% url 'PHR:Visit' En_id %}" style="line-height: 0.5;font-size: 12px;">Link</a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td  style="vertical-align: middle;font-size: 12px;">None</td>
                    <td  style="vertical-align: middle;font-size: 12px;">None</td>
                    <td  style="vertical-align: middle;font-size: 12px;">!</td>
                    <form  method="post" action="" novalidate>
                        {% csrf_token %}
                        <td>
                            <button class="btn btn-primary" type="submit" name="Report">Link</button>
                        </td>
                    </form>
                    <td>
                        <a class="btn btn-primary" href="">Link</a>
                    </td>
                </tr>

                {% endfor %}
                </tbody>
            </table>
        </div>


        <script src="https://cdn.staticfile.org/echarts/4.3.0/echarts.min.js"></script>
        <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
        <script src="https://cdn.bootcss.com/popper.js/1.15.0/umd/popper.js"></script>
        <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="https://cdn.staticfile.org/echarts/4.3.0/echarts.min.js"></script>
        <script type="text/javascript">
        </script>
    </body>
</html>

PHR/templates/Medications_History.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- 上述meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
        <!-- Bootstrap CSS -->
        <!-- <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"> -->

        <link href="{% static 'index/css/index.css' %}" rel="stylesheet"/>
        <style>
            .button:focus {
                outline: none;
                box-shadow: none;
            }
            ul {
                list-style-type: none;
                margin: 0;
                padding: 0;
                overflow: hidden;
                background-color: rgba(247, 247, 247, 0.8);
            }

            li {
                float: left;
            }

            li a {
                display: block;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }
            /*
            a,a:hover,a:active,a:visited,a:link,a:focus{
                -webkit-tap-highlight-color:rgba(0,0,0,0);
                -webkit-tap-highlight-color: transparent;
                outline:none;
                background: none;
                text-decoration: none;
            }background:#0000ff61;
            */


            .back:hover{
                color:#fff;
                background-color:#b3d7ff;
                border-color:#b3d7ff;
                text-decoration: none;
            }
            .table td, .table th {
                padding: 0.35rem;
            }
        </style>
        <title>Medications History</title>
    </head>
    <body>
        <ul>
            <li><a href="/PHR/index/" class="back">< Back</a></li>
            <li style="margin-left: 15%;">
                <h1 style="display: block;text-align: center;
                    padding: 14px 16px;color:#030303;font-size: 16px;font-family: Helvetica-bold;float: none;
                    font-weight: bold;">
                    Medication
                </h1>
            </li>
        </ul>

        <div class="container" style="padding: 0.2rem;overflow-y: auto;">
            <table class="table table-striped" style="line-height: 10px;font-size: 12px;text-align: center;font-family: Arial;">

                <tbody>

                {% for Name,Dose,Way,FreQ,Start,En_id in Medications_DataList1 %}
                <tr>
                    <td style="vertical-align: middle;font-size: 12px;word-break: break-all;" colspan="5">
                        {{Name}}
                    </td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'PHR:Visit' En_id %}" style="line-height: 0.5;font-size: 12px;">Link</a>
                    </td>
                </tr>
                <tr>
                    <td style="vertical-align: middle;font-size: 12px;">
                        {{Dose}}
                    </td>
                    <td style="vertical-align: middle;font-size: 12px;">
                        {{Way}}
                    </td>
                    <td style="vertical-align: middle;font-size: 12px;">
                        {{FreQ}}
                    </td>
                    <td style="vertical-align: middle;font-size: 12px;word-break: break-all;">
                        {{Start}}
                    </td>
                </tr>
                {% empty %}
                <tr><!--
                    <td style="vertical-align: middle;font-size: 12px;" colspan="5">Name</td>-->
                    <td style="vertical-align: middle;font-size: 12px;word-break: break-all;" colspan="4">
                        None
                    </td>
                    <td>
                        <a class="btn btn-primary" href="" style="line-height: 0.5;font-size: 12px;">Link</a>
                    </td>
                </tr>
                <tr>
                    <td style="vertical-align: middle;font-size: 12px;">
                        None
                    </td>
                    <td style="vertical-align: middle;font-size: 12px;">
                        None
                    </td>
                    <td style="vertical-align: middle;font-size: 12px;">
                        None
                    </td>
                    <td style="vertical-align: middle;font-size: 12px;word-break: break-all;">
                        None
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>


        <script src="https://cdn.staticfile.org/echarts/4.3.0/echarts.min.js"></script>
        <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
        <script src="https://cdn.bootcss.com/popper.js/1.15.0/umd/popper.js"></script>
        <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="https://cdn.staticfile.org/echarts/4.3.0/echarts.min.js"></script>
        <script type="text/javascript">
        </script>
    </body>
</html>